apiVersion: apps/v1
kind: Deployment
metadata:
  name: hm-app
spec:
  replicas: 3 # Number of replicas
  selector:
    matchLabels:
      app: hm-app
  template:
    metadata:
      labels:
        app: hm-app
    spec:
      containers:
        - name: hm-app
          image: CONTAINER_IMAGE # Replace with your Docker Hub image
          ports:
            - containerPort: 8080 # Replace with the port your Dash app uses
          imagePullPolicy: Always
