apiVersion: v1
kind: Service
metadata:
  name: dash-service
spec:
  selector:
    app: hm-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 # Replace with your Dash app port
  type: LoadBalancer
